### ISSUE TITLE
arduino.h typo

### ISSUE THREAD

**Issue by bervoiv** [allthingstalk/arduino-lora#3]
Hi Guys,

In my Arduino IDE I get an error on the #include <arduino.h> in some ccp files.
I fixed this locally, I think this should be with a capital letter.

Regards,
Ivo

**Comment by jan-bogaerts** [comment]
Hi,
Thanks for the feedback.  there were some updates recently which should not yet have been pushed to production....
Are you perhaps on a linux or mac machine (they are more sensitive for this)? Could you perhaps let me know which files gave a problem?  I'm on windows, and don't get this issue.
Thanks.

**Comment by bervoiv** [comment]
Hi,
I'm on a linux machine indeed. 
The problem occurs in:
- ATT_Lora_IOT.ccp
- EmbitLoRaModem.ccp
- MicrochipLoRaModem.ccp

Regards,
Ivo
