### ISSUE TITLE
Wire.h

### ISSUE THREAD

**Issue by AlainMus** [allthingstalk/arduino-lora#7]
I just bought the Att Lora Development Kit, but when i try the demo, or any off the examples it gives an error on the #include<Wire.h> line.

"fatal error: Wire.h: No such file or directory"

i followed the step on http://docs.smartliving.io/kits/lora/  but it doesnt seem to work
it compiles when i comment the line  and i see the following in the serial monitor
ATT lib version: 1.1
modem initialized
Ready to send data
Data: 0
Sending payload:

but i cannot do anything

how can i fix the no file error?

**Comment by jan-bogaerts** [comment]
This is a sodaq related issue. See response to support ticket for more info
